"""
Shared captcha challenge store.

Any captcha-style module (text-in-modal, image-based, future audio, etc.)
needs the same three things: generate a code, remember it against a user
with an expiry, and check an answer against it. Keeping that logic in one
place means every captcha variant behaves identically underneath - only
how the code is *shown* to the user differs per module.

Challenges are keyed by (guild_id, user_id, method), not just
(guild_id, user_id). Without the method in the key, a code generated by
ANY method could be submitted into ANY other method's "enter code" modal
for the same user - e.g. a stale/leftover Button or text-Captcha message
(persistent views keep old messages clickable even after an admin switches
methods) could hand a user an instantly-visible code, which they could then
submit into an Email or Phone verification's modal, "verifying" without
ever actually proving control of that inbox or phone number at all. Scoping
by method closes that gap: a code is only ever checkable by the exact flow
that created it.

In-memory only: fine for a single-process bot. If you ever run multiple
processes/shards sharing state, swap this for Redis or the DB.
"""

import secrets
import string
import time
from typing import Any

_CHALLENGES: dict[tuple[int, int, str], dict[str, Any]] = (
    {}
)  # (guild_id, user_id, method) -> {code, expires_at}
_DEFAULT_TTL_SECONDS = 300

# Characters that are easy to confuse (0/O, 1/I) are excluded from every captcha variant.
_SAFE_ALPHANUMERIC = "".join(
    c for c in string.ascii_uppercase + string.digits if c not in "0O1I"
)
_SAFE_NUMERIC = "".join(c for c in string.digits if c not in "01")


def generate_code(length: int = 6, kind: str = "alphanumeric") -> str:
    # secrets.choice() (not random.choice()/random.choices()) - this code IS
    # the secret being verified, so it needs a cryptographically secure
    # source. Python's `random` module uses a Mersenne Twister PRNG, which
    # is fast but NOT safe for anything security-sensitive: its output is
    # statistically predictable from past outputs, so `secrets` (backed by
    # os.urandom()) is required here, same as for any token, password, or
    # session ID.
    alphabet = _SAFE_NUMERIC if kind == "numeric" else _SAFE_ALPHANUMERIC
    return "".join(secrets.choice(alphabet) for _ in range(length))


def store_challenge(
    guild_id: int,
    user_id: int,
    method: str,
    code: str,
    ttl_seconds: int = _DEFAULT_TTL_SECONDS,
) -> None:
    _cleanup_expired()
    _CHALLENGES[(guild_id, user_id, method)] = {
        "code": code,
        "expires_at": time.time() + ttl_seconds,
    }


def check_answer(
    guild_id: int, user_id: int, method: str, answer: str
) -> tuple[bool, str | None]:
    """
    Consumes the stored challenge (pass or fail) so each generated code is
    single-use - a fresh click of Verify is required to try again.

    method must match the method that created the challenge - a code
    generated by "captcha" is never checkable against "email", "phone", etc.,
    even for the same (guild_id, user_id).

    Returns (passed, failure_reason). failure_reason is None on success.
    """
    entry = _CHALLENGES.pop((guild_id, user_id, method), None)

    if entry is None:
        return False, "No active code found. Click Verify to get a new one."
    if time.time() > entry["expires_at"]:
        return False, "That code expired."
    if answer.strip().upper() == entry["code"]:
        return True, None
    return False, "That code didn't match."


def _cleanup_expired() -> None:
    now = time.time()
    expired = [key for key, entry in _CHALLENGES.items() if entry["expires_at"] < now]
    for key in expired:
        _CHALLENGES.pop(key, None)
